apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: data-platform-api-request-reads-cache-manager-rmq-kube
  name: data-platform-api-request-reads-cache-manager-rmq-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-platform-api-request-reads-cache-manager-rmq-kube
      app: ORDERS
  template:
    metadata:
      labels:
        run: data-platform-api-request-reads-cache-manager-rmq-kube
        app: ORDERS
    spec:
      hostname: data-platform-api-request-reads-cache-manager-rmq-kube
      containers:
        - name: data-platform-api-request-reads-cache-manager-rmq-kube
          image: latonaio/data-platform-api-request-reads-cache-manager-rmq-kube
          imagePullPolicy: Always
          env:
            - name: "RMQ_USER"
              value: "XXXX"
            - name: "RMQ_PASS"
              value: "XXXX"
            - name: "RMQ_ADDRESS"
              value: "rabbitmq"
            - name: "RMQ_PORT"
              value: "5672"
            - name: "RMQ_QUEUE_FROM"
              value: "data-platform-api-request-reads-cache-manager-queue"
            - name: "RMQ_SESSION_CONTROL_QUEUE"
              value: "data-platform-api-request-reads-cache-manager-receive-queue"
            - name: "RMQ_VHOST"
              value: "data-platform"
            - name: "REDIS_ADDR"
              value: "redis-kube"
            - name: "REDIS_PORT"
              value: "6379"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: data-platform-api-request-reads-cache-manager-rmq-kube
  name: data-platform-api-request-reads-cache-manager-rmq-kube
spec:
  selector:
    run: data-platform-api-request-reads-cache-manager-rmq-kube
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30751
